export type AssetCategory =
  | "country"
  | "people"
  | "economy"
  | "industry"
  | "objects"
  | "politics"
  | "hands";

export type AssetDefinition = {
  id: string;
  name: string;
  category: AssetCategory;
  tags: string[];
  src: string;
  type: "svg" | "image";
};

export const assets: AssetDefinition[] = [
  {
    id: "usa",
    name: "美国",
    category: "country",
    tags: ["美国", "USA", "America", "国家", "美国国旗"],
    src: "/assets/countries/usa.svg",
    type: "svg",
  },
  {
    id: "iran",
    name: "伊朗",
    category: "country",
    tags: ["伊朗", "Iran", "国家"],
    src: "/assets/countries/iran.svg",
    type: "svg",
  },
  {
    id: "china",
    name: "中国",
    category: "country",
    tags: ["中国", "China", "国家"],
    src: "/assets/countries/china.svg",
    type: "svg",
  },
  {
    id: "russia",
    name: "俄罗斯",
    category: "country",
    tags: ["俄罗斯", "Russia", "国家"],
    src: "/assets/countries/russia.svg",
    type: "svg",
  },
  {
    id: "india",
    name: "印度",
    category: "country",
    tags: ["印度", "India", "国家"],
    src: "/assets/countries/india.svg",
    type: "svg",
  },
  {
    id: "japan",
    name: "日本",
    category: "country",
    tags: ["日本", "Japan", "国家"],
    src: "/assets/countries/japan.svg",
    type: "svg",
  },
  {
    id: "uk",
    name: "英国",
    category: "country",
    tags: ["英国", "UK", "Britain", "国家"],
    src: "/assets/countries/uk.svg",
    type: "svg",
  },
  {
    id: "germany",
    name: "德国",
    category: "country",
    tags: ["德国", "Germany", "国家"],
    src: "/assets/countries/germany.svg",
    type: "svg",
  },
  {
    id: "saudi",
    name: "沙特",
    category: "country",
    tags: ["沙特", "Saudi", "中东", "国家"],
    src: "/assets/countries/saudi.svg",
    type: "svg",
  },
  {
    id: "businessman",
    name: "商人",
    category: "people",
    tags: ["人物", "商人", "businessman", "西装"],
    src: "/assets/people/businessman.svg",
    type: "svg",
  },
  {
    id: "worker",
    name: "工人",
    category: "people",
    tags: ["人物", "工人", "worker"],
    src: "/assets/people/worker.svg",
    type: "svg",
  },
  {
    id: "politician",
    name: "政客",
    category: "people",
    tags: ["人物", "政客", "politician"],
    src: "/assets/people/politician.svg",
    type: "svg",
  },
  {
    id: "soldier",
    name: "士兵",
    category: "people",
    tags: ["士兵", "军人", "soldier", "军事"],
    src: "/assets/people/soldier.svg",
    type: "svg",
  },
  {
    id: "crowd",
    name: "人群",
    category: "people",
    tags: ["人群", "民众", "crowd"],
    src: "/assets/people/crowd.svg",
    type: "svg",
  },
  {
    id: "money",
    name: "钱",
    category: "economy",
    tags: ["钱", "money", "现金"],
    src: "/assets/economy/money.svg",
    type: "svg",
  },
  {
    id: "dollar",
    name: "美元",
    category: "economy",
    tags: ["美元", "dollar", "USD", "钱"],
    src: "/assets/economy/dollar.svg",
    type: "svg",
  },
  {
    id: "bank",
    name: "银行",
    category: "economy",
    tags: ["银行", "bank"],
    src: "/assets/economy/bank.svg",
    type: "svg",
  },
  {
    id: "stock",
    name: "股票",
    category: "economy",
    tags: ["股票", "stock"],
    src: "/assets/economy/stock.svg",
    type: "svg",
  },
  {
    id: "chart",
    name: "图表",
    category: "economy",
    tags: ["图表", "chart", "经济"],
    src: "/assets/economy/chart.svg",
    type: "svg",
  },
  {
    id: "coins",
    name: "硬币",
    category: "economy",
    tags: ["硬币", "coins", "钱"],
    src: "/assets/economy/coins.svg",
    type: "svg",
  },
  {
    id: "wallet",
    name: "钱包",
    category: "economy",
    tags: ["钱包", "wallet", "钱"],
    src: "/assets/economy/wallet.svg",
    type: "svg",
  },
  {
    id: "embargo",
    name: "禁运",
    category: "economy",
    tags: ["禁运", "embargo", "制裁", "封锁"],
    src: "/assets/economy/embargo.svg",
    type: "svg",
  },
  {
    id: "factory",
    name: "工厂",
    category: "industry",
    tags: ["工厂", "factory", "工业"],
    src: "/assets/industry/factory.svg",
    type: "svg",
  },
  {
    id: "oil",
    name: "石油",
    category: "industry",
    tags: ["石油", "oil"],
    src: "/assets/industry/oil.svg",
    type: "svg",
  },
  {
    id: "oil-factory",
    name: "石油工厂",
    category: "industry",
    tags: ["石油", "工厂", "oil", "oil-factory", "炼油"],
    src: "/assets/industry/oil-factory.svg",
    type: "svg",
  },
  {
    id: "pipeline",
    name: "管道",
    category: "industry",
    tags: ["管道", "pipeline", "石油"],
    src: "/assets/industry/pipeline.svg",
    type: "svg",
  },
  {
    id: "power",
    name: "电力",
    category: "industry",
    tags: ["电力", "power", "能源"],
    src: "/assets/industry/power.svg",
    type: "svg",
  },
  {
    id: "oil-barrel",
    name: "油桶",
    category: "industry",
    tags: ["油桶", "石油", "oil-barrel", "原油"],
    src: "/assets/industry/oil-barrel.svg",
    type: "svg",
  },
  {
    id: "derrick",
    name: "井架",
    category: "industry",
    tags: ["井架", "derrick", "石油", "钻井"],
    src: "/assets/industry/derrick.svg",
    type: "svg",
  },
  {
    id: "tanker",
    name: "油轮",
    category: "industry",
    tags: ["油轮", "tanker", "船", "石油"],
    src: "/assets/industry/tanker.svg",
    type: "svg",
  },
  {
    id: "phone",
    name: "手机",
    category: "objects",
    tags: ["手机", "phone"],
    src: "/assets/objects/phone.svg",
    type: "svg",
  },
  {
    id: "computer",
    name: "电脑",
    category: "objects",
    tags: ["电脑", "computer"],
    src: "/assets/objects/computer.svg",
    type: "svg",
  },
  {
    id: "car",
    name: "汽车",
    category: "objects",
    tags: ["汽车", "car"],
    src: "/assets/objects/car.svg",
    type: "svg",
  },
  {
    id: "house",
    name: "房子",
    category: "objects",
    tags: ["房子", "house"],
    src: "/assets/objects/house.svg",
    type: "svg",
  },
  {
    id: "money-box",
    name: "钱箱",
    category: "objects",
    tags: ["钱箱", "money-box", "保险箱", "箱子"],
    src: "/assets/objects/money-box.svg",
    type: "svg",
  },
  {
    id: "globe",
    name: "地球",
    category: "objects",
    tags: ["地球", "世界", "globe", "地图"],
    src: "/assets/objects/globe.svg",
    type: "svg",
  },
  {
    id: "plane",
    name: "飞机",
    category: "objects",
    tags: ["飞机", "plane", "航空"],
    src: "/assets/objects/plane.svg",
    type: "svg",
  },
  {
    id: "ship",
    name: "船",
    category: "objects",
    tags: ["船", "ship", "海运"],
    src: "/assets/objects/ship.svg",
    type: "svg",
  },
  {
    id: "newspaper",
    name: "报纸",
    category: "objects",
    tags: ["报纸", "新闻", "newspaper"],
    src: "/assets/objects/newspaper.svg",
    type: "svg",
  },
  {
    id: "chain",
    name: "锁链",
    category: "objects",
    tags: ["锁链", "chain", "制裁", "束缚"],
    src: "/assets/objects/chain.svg",
    type: "svg",
  },
  {
    id: "missile",
    name: "导弹",
    category: "objects",
    tags: ["导弹", "missile", "军事"],
    src: "/assets/objects/missile.svg",
    type: "svg",
  },
  {
    id: "government",
    name: "政府",
    category: "politics",
    tags: ["政府", "government"],
    src: "/assets/politics/government.svg",
    type: "svg",
  },
  {
    id: "election",
    name: "选举",
    category: "politics",
    tags: ["选举", "election"],
    src: "/assets/politics/election.svg",
    type: "svg",
  },
  {
    id: "flag",
    name: "旗帜",
    category: "politics",
    tags: ["旗帜", "flag", "国旗"],
    src: "/assets/politics/flag.svg",
    type: "svg",
  },
  {
    id: "sanctions",
    name: "制裁",
    category: "politics",
    tags: ["制裁", "sanctions", "禁止"],
    src: "/assets/politics/sanctions.svg",
    type: "svg",
  },
  {
    id: "capitol",
    name: "国会",
    category: "politics",
    tags: ["国会", "capitol", "白宫", "政府"],
    src: "/assets/politics/capitol.svg",
    type: "svg",
  },
  {
    id: "gavel",
    name: "法槌",
    category: "politics",
    tags: ["法槌", "gavel", "法律", "制裁"],
    src: "/assets/politics/gavel.svg",
    type: "svg",
  },
  {
    id: "un",
    name: "联合国",
    category: "politics",
    tags: ["联合国", "UN", "国际"],
    src: "/assets/politics/un.svg",
    type: "svg",
  },
  {
    id: "arrow",
    name: "箭头",
    category: "objects",
    tags: ["箭头", "arrow"],
    src: "/assets/objects/arrow.svg",
    type: "svg",
  },
  {
    id: "lock",
    name: "锁",
    category: "objects",
    tags: ["锁", "lock", "封锁"],
    src: "/assets/objects/lock.svg",
    type: "svg",
  },
  {
    id: "hand-right",
    name: "右手",
    category: "hands",
    tags: ["手", "hand", "right"],
    src: "/assets/hands/hand-right.png",
    type: "image",
  },
  {
    id: "hand-left",
    name: "左手",
    category: "hands",
    tags: ["手", "hand", "left"],
    src: "/assets/hands/hand-left.png",
    type: "image",
  },
];

const assetsById = new Map(assets.map((asset) => [asset.id, asset]));

export function getAsset(id: string): AssetDefinition | undefined {
  return assetsById.get(id);
}

export function getAssetOrThrow(id: string): AssetDefinition {
  const asset = assetsById.get(id);
  if (!asset) {
    throw new Error(`Asset not found: "${id}"`);
  }
  return asset;
}
